package vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import controlador.controllerMedicamentos;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.modelCompuestos;

/**
 *
 * @author AMolinaDeveloper
 */
public class BuscarMedicamentos extends javax.swing.JInternalFrame {
public DefaultTableModel dtm;
private int x;
private int y;
    /**
     * Creates new form BuscarMedicamentos
     */
    public BuscarMedicamentos() {
        initComponents();
     TextAutoCompleterCompuestos(this.Buscar);   
    }
public final void TextAutoCompleterCompuestos(JTextField busc) {
        TextAutoCompleter Tac = new TextAutoCompleter(busc);
        //controllerLaboratorio cl = new controllerLaboratorio();
        modelCompuestos.setOp("D");
        modelCompuestos.setBusc("");
        ResultSet rs = modelCompuestos.queryCompuestos();
        try {
            Tac.removeAllItems();
            while (rs.next()) {
                Object[] obj = new Object[1];
                obj[0] = rs.getString("COMPONENTE");
                Tac.addItem(obj[0]);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableComponentes = new javax.swing.JTable();
        Buscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMedicamentos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar por compuestos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/connections.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(990, 437));
        setMinimumSize(new java.awt.Dimension(990, 437));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Realizar busqueda por compuestos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N

        jTableComponentes.setBackground(new java.awt.Color(255, 204, 255));
        jTableComponentes.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTableComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "###", "Compuestos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableComponentes.setToolTipText("Borrar con [Supr]");
        jTableComponentes.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableComponentes.getTableHeader().setReorderingAllowed(false);
        jTableComponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableComponentesMouseClicked(evt);
            }
        });
        jTableComponentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableComponentesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableComponentes);

        Buscar.setBackground(new java.awt.Color(255, 204, 204));
        Buscar.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Buscar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Buscar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Ingrese compuestos de medicamentos a ser buscados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Buscar.setCaretColor(new java.awt.Color(51, 204, 255));
        Buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarFocusGained(evt);
            }
        });
        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarKeyReleased(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Medicamentos que contienen los compuestos ingresados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N

        jTableMedicamentos.setBackground(new java.awt.Color(255, 255, 204));
        jTableMedicamentos.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTableMedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMedicamentos.setGridColor(new java.awt.Color(204, 204, 204));
        jTableMedicamentos.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableMedicamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableMedicamentos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Buscar)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Close.png"))); // NOI18N
        jMenu4.setText("CERRAR VENTANA");
        jMenu4.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableComponentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableComponentesMouseClicked
        //       dtm= (DefaultTableModel) this.jTableDetallesComp.getModel();
        //        if (evt.getButton() == MouseEvent.BUTTON1) {
            //
            //            jTableDetallesComp.getColumnModel().getColumn(0).setMaxWidth(0);
            //            jTableDetallesComp.getColumnModel().getColumn(0).setMinWidth(0);
            //            jTableDetallesComp.getColumnModel().getColumn(0).setPreferredWidth(0);
            //            jTableDetallesComp.getColumnModel().getColumn(0).setWidth(0);
            //            System.out.println("Selecciono : "+this.jTableDetallesComp.getSelectedRow());
            //            dtm.removeRow(this.jTableDetallesComp.getSelectedRow());
            //        }
    }//GEN-LAST:event_jTableComponentesMouseClicked

    private void jTableComponentesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableComponentesKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            dtm = (DefaultTableModel) this.jTableComponentes.getModel();
            System.out.println("Selecciono : " + this.jTableComponentes.getSelectedRow());
            dtm.removeRow(this.jTableComponentes.getSelectedRow());
            
            
            int x = jTableComponentes.getRowCount();
            int y = 0;
            int[] R = new int[x];
            String concat = "";
            while (y < x) {
                R[y] = Integer.parseInt(this.jTableComponentes.getValueAt(y, 0).toString());
                y++;
            }
            System.out.println("la tabla tiene filas " + x);
            int arregloOrdenado[] = Medicamentos.burbuja(R);
            String arreglo = "";
            //imprimimos el arreglo ordenado.
            for (int i = 0; i < arregloOrdenado.length; i++) {
                arreglo = arreglo + "-" + arregloOrdenado[i];

            }

            System.out.print(arreglo + " y arregladito");
            
            
                   controllerMedicamentos.setOp("R");
        controllerMedicamentos.setBusc(arreglo);
        controllerMedicamentos.consultarMedicamentosBuscadosXCompuestos(dtm);
            
        }
    }//GEN-LAST:event_jTableComponentesKeyPressed

    private void BuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarFocusGained

    }//GEN-LAST:event_BuscarFocusGained

    private void BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyPressed
      
    }//GEN-LAST:event_BuscarKeyPressed

    private void BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyReleased
                try {
            if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
                modelCompuestos.setOp("S");
                modelCompuestos.setBusc(this.Buscar.getText());
                ResultSet rs = modelCompuestos.queryCompuestos();

                if (rs.next()) {
                    int r = this.jTableMedicamentos.getRowCount();
                    System.out.println("next : " + rs.getString("###") + " Row : " + r);
                    dtm = (DefaultTableModel) this.jTableComponentes.getModel();

                    Object[] obj = new Object[2];
                    obj[0] = rs.getString("###");
                                       obj[1] = rs.getString("COMPONENTE");
                    dtm.addRow(obj);
                    this.Buscar.setText(null);
                    this.Buscar.requestFocus();
                    
 int x = jTableComponentes.getRowCount();
            int y = 0;
            int[] R = new int[x];
            String concat = "";
            while (y < x) {
                R[y] = Integer.parseInt(this.jTableComponentes.getValueAt(y, 0).toString());
                y++;
            }
            System.out.println("la tabla tiene filas " + x);
            int arregloOrdenado[] = Medicamentos.burbuja(R);
            String arreglo = "";
            //imprimimos el arreglo ordenado.
            for (int i = 0; i < arregloOrdenado.length; i++) {
                arreglo = arreglo + "-" + arregloOrdenado[i];

            }

            System.out.print(arreglo + " y arregladito");
            
            //////////////////////////////////////////////////////////////////////////////////////////////////
            //////////////////////////////////////////////////////////////////////////////////////////////////
                    controllerMedicamentos.setOp("R");
        controllerMedicamentos.setBusc(arreglo);
        controllerMedicamentos.consultarMedicamentosBuscadosXCompuestos(dtm);
       
            
            
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(BuscarMedicamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BuscarKeyReleased

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1

        System.out.println("Coordenadas: ("+ubicacion.x+","+ubicacion.y+")");//2
        setLocation((ubicacion.x-0), (ubicacion.y)-230);//3
        //239 268
    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked

    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        this.toFront();
        x = evt.getX();

        y = evt.getY();
    }//GEN-LAST:event_jMenuBar1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableComponentes;
    public static javax.swing.JTable jTableMedicamentos;
    // End of variables declaration//GEN-END:variables
}
