package vista;

import controlador.controllerClientes;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMolinaDeveloper
 */
public class Clientes extends javax.swing.JInternalFrame {
 private int x;
    private int y;
    public DefaultTableModel dtm;

    public void clear() {
        this.txtcodclientes.setText(null);
        this.Nombres.setText(null);
        this.Dni.setText(null);
        this.Ruc.setText(null);
        this.Direccion.setText(null);
        this.Telefono.setText(null);
        this.Nombres.requestFocus();
    }

    /**
     * Creates new form Cliente
     */
    public Clientes() {
        initComponents();

    }

    public void insertClientes() {
        if( validator.novacios("8-3", 2, Dni,Nombres)==false){
        if(this.txtcodclientes.getText().length()>0){
        
        }
            controllerClientes.setOp("I");
        controllerClientes.setCod(0);
        controllerClientes.setNomb(this.Nombres.getText());
        controllerClientes.setDni(this.Dni.getText());
        controllerClientes.setDir(this.Direccion.getText());
        controllerClientes.setRuc(this.Ruc.getText());
        controllerClientes.setFono(this.Telefono.getText());
        this.txtmsg.setText(controllerClientes.mntoClientes());
        controllerClientes.setOp("D");
        controllerClientes.setBusc(this.Nombres.getText());
        controllerClientes.consultarClientes(dtm);
        JOptionPane.showMessageDialog(null,"Nuevo Cliente ingresado \n "+this.Nombres.getText(),"Nuevo cliente",JOptionPane.INFORMATION_MESSAGE);
        clear();
        }
    }

    public void updateClientes() {
         if( validator.novacios("8", 1, Dni)==false){
        controllerClientes.setOp("U");
        controllerClientes.setCod(Integer.parseInt(this.txtcodclientes.getText()));
        controllerClientes.setNomb(this.Nombres.getText());
        controllerClientes.setDni(this.Dni.getText());
        controllerClientes.setDir(this.Direccion.getText());
        controllerClientes.setRuc(this.Ruc.getText());
        controllerClientes.setFono(this.Telefono.getText());
        controllerClientes.mntoClientes();
        controllerClientes.setOp("D");
        controllerClientes.setBusc(this.Nombres.getText());
        controllerClientes.consultarClientes(dtm);
         JOptionPane.showMessageDialog(null,"Cliente actualizado correctamente.","Cliente actualizado",JOptionPane.INFORMATION_MESSAGE);
        clear();
         }    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Nombres = new javax.swing.JTextField();
        Dni = new javax.swing.JTextField();
        Ruc = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        txtmsg = new javax.swing.JLabel();
        txtcodclientes = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        buscClie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario de registro de clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/connections.png"))); // NOI18N
        setInheritsPopupMenu(true);
        setMinimumSize(new java.awt.Dimension(901, 472));
        setPreferredSize(new java.awt.Dimension(901, 472));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(901, 400));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        Nombres.setName("Nombres");
        Nombres.setBackground(new java.awt.Color(244, 245, 242));
        Nombres.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Nombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombres.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Nombres[Minimo 3 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Nombres.setCaretColor(new java.awt.Color(51, 204, 255));
        Nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombresKeyReleased(evt);
            }
        });

        Dni.setName("Dni");
        Dni.setBackground(new java.awt.Color(244, 245, 242));
        Dni.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Dni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Dni.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Dni[8 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Dni.setCaretColor(new java.awt.Color(51, 204, 255));
        Dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DniKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DniKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DniKeyTyped(evt);
            }
        });

        Ruc.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        Ruc.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ruc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Ruc[11 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Ruc.setCaretColor(new java.awt.Color(51, 204, 255));
        Ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RucKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RucKeyTyped(evt);
            }
        });

        Telefono.setBackground(new java.awt.Color(244, 245, 242));
        Telefono.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Telefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), " Telefono o Celular[Hasta 9 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Telefono.setCaretColor(new java.awt.Color(51, 204, 255));
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Direccion.setBackground(new java.awt.Color(244, 245, 242));
        Direccion.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Direccion[Hasta 250 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Direccion.setCaretColor(new java.awt.Color(51, 204, 255));
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DireccionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DireccionKeyReleased(evt);
            }
        });

        txtmsg.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        txtmsg.setForeground(new java.awt.Color(102, 0, 0));
        txtmsg.setText("DATOS CARGADOS.");
        txtmsg.setMaximumSize(new java.awt.Dimension(171, 16));
        txtmsg.setMinimumSize(new java.awt.Dimension(171, 16));
        txtmsg.setPreferredSize(new java.awt.Dimension(171, 16));
        txtmsg.setRequestFocusEnabled(false);

        txtcodclientes.setEditable(false);
        txtcodclientes.setBackground(new java.awt.Color(255, 255, 153));
        txtcodclientes.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                        .addComponent(Direccion)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Nombres))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcodclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros de clientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        buscClie.setBackground(new java.awt.Color(255, 204, 204));
        buscClie.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        buscClie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        buscClie.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Button.background"), 1, true), "Realizar búsqueda de cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        buscClie.setCaretColor(new java.awt.Color(51, 204, 255));
        buscClie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscClieKeyPressed(evt);
            }
        });

        jTableClientes.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "###", "Cliente", "DNI", "RUC", "Direccion", "Fono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableClientes.getTableHeader().setReorderingAllowed(false);
        jTableClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTableClientesMouseDragged(evt);
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jTableClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setResizable(false);
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            jTableClientes.getColumnModel().getColumn(2).setResizable(false);
            jTableClientes.getColumnModel().getColumn(3).setResizable(false);
            jTableClientes.getColumnModel().getColumn(4).setResizable(false);
            jTableClientes.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(buscClie))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(buscClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Add.png"))); // NOI18N
        jMenu1.setText("NUEVO[F4]");
        jMenu1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/OK.png"))); // NOI18N
        jMenu2.setText("REGISTRAR[F5]");
        jMenu2.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Sync.png"))); // NOI18N
        jMenu3.setText("ACTUALIZAR[F6]");
        jMenu3.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Close.png"))); // NOI18N
        jMenu4.setText("CERRAR VENTANA");
        jMenu4.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        int sel = this.jTableClientes.getSelectedRow();
        this.txtcodclientes.setText(this.jTableClientes.getValueAt(sel, 0).toString());
        this.Nombres.setText(this.jTableClientes.getValueAt(sel, 1).toString());
        this.Dni.setText(this.jTableClientes.getValueAt(sel, 2).toString());
        this.Ruc.setText(this.jTableClientes.getValueAt(sel, 3).toString());
        this.Direccion.setText(this.jTableClientes.getValueAt(sel, 4).toString());
        this.Telefono.setText(this.jTableClientes.getValueAt(sel, 5).toString());
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void NombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombresKeyPressed

    }//GEN-LAST:event_NombresKeyPressed

    private void buscClieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscClieKeyPressed
        controllerClientes.setOp("D");
        controllerClientes.setBusc(this.buscClie.getText());
        controllerClientes.consultarClientes(dtm);
        
    }//GEN-LAST:event_buscClieKeyPressed

    private void DniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyPressed




    }//GEN-LAST:event_DniKeyPressed

    private void TelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyPressed


    }//GEN-LAST:event_TelefonoKeyPressed

    private void DireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyPressed


    }//GEN-LAST:event_DireccionKeyPressed

    private void DniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyTyped
       
        validator.solonumeros(evt, Dni, 8);
    }//GEN-LAST:event_DniKeyTyped

    private void jTableClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClientesKeyPressed
if(evt.getExtendedKeyCode()==KeyEvent.VK_F4){
clear();
}
if (evt.getKeyCode() == 38 || evt.getKeyCode() == 40) {
            int sel = this.jTableClientes.getSelectedRow();
        this.txtcodclientes.setText(this.jTableClientes.getValueAt(sel, 0).toString());
        this.Nombres.setText(this.jTableClientes.getValueAt(sel, 1).toString());
        this.Dni.setText(this.jTableClientes.getValueAt(sel, 2).toString());
        this.Ruc.setText(this.jTableClientes.getValueAt(sel, 3).toString());
        this.Direccion.setText(this.jTableClientes.getValueAt(sel, 4).toString());
        this.Telefono.setText(this.jTableClientes.getValueAt(sel, 5).toString());
}
    }//GEN-LAST:event_jTableClientesKeyPressed

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
validator.solonumeros(evt, Telefono, 9);
    }//GEN-LAST:event_TelefonoKeyTyped

    private void TelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
            insertClientes();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                updateClientes();
            }else{
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
                clear();
            }}
        }
    }//GEN-LAST:event_TelefonoKeyReleased

    private void DniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
            insertClientes();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                updateClientes();
            }else{
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
                clear();
            }}
        }
  
    }//GEN-LAST:event_DniKeyReleased

    private void NombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombresKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
            insertClientes();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                updateClientes();
            }else{
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
                clear();
            }}
        }      
    }//GEN-LAST:event_NombresKeyReleased

    private void DireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
            insertClientes();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                updateClientes();
            }else{
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
                clear();
            }}
        }
    }//GEN-LAST:event_DireccionKeyReleased

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        this.toFront();
        x = evt.getX();

    y = evt.getY(); 
    }//GEN-LAST:event_jMenuBar1MousePressed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
  Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1
  
    System.out.println("Coordenadas: ("+ubicacion.x+","+ubicacion.y+")");//2
    setLocation((ubicacion.x-0), (ubicacion.y)-230);//3
    //239 268
    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jTableClientesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseDragged

    }//GEN-LAST:event_jTableClientesMouseDragged

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked

    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
clear(); 
this.jMenu1.setSelected(false);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
insertClientes();
this.jMenu2.setSelected(false);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
if(this.txtcodclientes.getText().length()==0){
JOptionPane.showMessageDialog(null,"Por favor seleccione un cliente de la tabla.","Seleccione cliente",JOptionPane.ERROR_MESSAGE);
}else{        updateClientes();}
this.jMenu3.setSelected(false);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void RucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RucKeyTyped
        validator.solonumeros(evt, Ruc, 11);
    }//GEN-LAST:event_RucKeyTyped

    private void RucKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RucKeyReleased
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
            insertClientes();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                updateClientes();
            }else{
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
                clear();
            }}
        }

    }//GEN-LAST:event_RucKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Dni;
    private javax.swing.JTextField Nombres;
    private javax.swing.JTextField Ruc;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField buscClie;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableClientes;
    private javax.swing.JTextField txtcodclientes;
    private javax.swing.JLabel txtmsg;
    // End of variables declaration//GEN-END:variables
}
