/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import controlador.controllerMedicamentos;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.modelMedicamentos;

/**
 *
 * @author AlvaroMolina
 */
public class Formulas extends javax.swing.JInternalFrame {

    public TextAutoCompleter Tac;
    private int x;
    private int y;
private DefaultTableModel dtm;
    /**
     * Creates new form Formulas
     */
    public Formulas() {
        initComponents();
        TextAutoCompleterMedicamento(this.Insumos);
    }

    public final void TextAutoCompleterMedicamento(JTextField busc) {
        Tac = new TextAutoCompleter(busc);
        //controllerLaboratorio cl = new controllerLaboratorio();
        modelMedicamentos.setOp("D");
        modelMedicamentos.setBusc("");
        ResultSet rs = modelMedicamentos.queryMedicamentos();
        try {
            Tac.removeAllItems();

            while (rs.next()) {
                Object[] obj = new Object[1];
                obj[0] = rs.getString("MEDICAMENTO");
                Tac.addItem(obj[0]);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Nombre = new javax.swing.JTextField();
        Insumos = new javax.swing.JTextField();
        txtcodlabor = new javax.swing.JTextField();
        txtmsg = new javax.swing.JLabel();
        Costo = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        Presentacion = new javax.swing.JTextField();
        laboratorio = new javax.swing.JTextField();
        Fraccionable = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        CantXPaq = new javax.swing.JTextField();
        PrecioUnit = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        StockDetallado = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLaborat = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Formulas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        Nombre.setName("Nombre");
        Nombre.setBackground(new java.awt.Color(244, 245, 242));
        Nombre.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Nombre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Nombre.setCaretColor(new java.awt.Color(51, 204, 255));
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreKeyPressed(evt);
            }
        });

        Insumos.setBackground(new java.awt.Color(244, 245, 242));
        Insumos.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Insumos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Insumos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Insumos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Insumos.setCaretColor(new java.awt.Color(51, 204, 255));
        Insumos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InsumosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InsumosKeyReleased(evt);
            }
        });

        txtcodlabor.setEditable(false);
        txtcodlabor.setBackground(new java.awt.Color(255, 255, 204));
        txtcodlabor.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        txtcodlabor.setMaximumSize(new java.awt.Dimension(100, 28));
        txtcodlabor.setMinimumSize(new java.awt.Dimension(100, 28));
        txtcodlabor.setPreferredSize(new java.awt.Dimension(100, 28));

        txtmsg.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        txtmsg.setForeground(new java.awt.Color(102, 0, 0));
        txtmsg.setText("DATOS CARGADOS.");
        txtmsg.setMaximumSize(new java.awt.Dimension(171, 16));
        txtmsg.setMinimumSize(new java.awt.Dimension(171, 16));
        txtmsg.setPreferredSize(new java.awt.Dimension(171, 16));
        txtmsg.setRequestFocusEnabled(false);

        Costo.setBackground(new java.awt.Color(255, 255, 204));
        Costo.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Costo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Costo.setText("0");
        Costo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Costo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Costo.setCaretColor(new java.awt.Color(51, 204, 255));
        Costo.setEnabled(false);
        Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoActionPerformed(evt);
            }
        });
        Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoKeyTyped(evt);
            }
        });

        Precio.setBackground(new java.awt.Color(255, 255, 204));
        Precio.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Precio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Precio.setText("0");
        Precio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Precio", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Precio.setCaretColor(new java.awt.Color(51, 204, 255));
        Precio.setEnabled(false);
        Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioKeyTyped(evt);
            }
        });

        Cantidad.setBackground(new java.awt.Color(244, 245, 242));
        Cantidad.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Cantidad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Cantidad.setCaretColor(new java.awt.Color(51, 204, 255));
        Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CantidadKeyReleased(evt);
            }
        });

        Presentacion.setBackground(new java.awt.Color(255, 255, 204));
        Presentacion.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Presentacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Presentacion.setText("0");
        Presentacion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Presentacion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Presentacion.setCaretColor(new java.awt.Color(51, 204, 255));
        Presentacion.setEnabled(false);
        Presentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresentacionActionPerformed(evt);
            }
        });
        Presentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PresentacionKeyTyped(evt);
            }
        });

        laboratorio.setBackground(new java.awt.Color(255, 255, 204));
        laboratorio.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        laboratorio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        laboratorio.setText("0");
        laboratorio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Laboratorio", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        laboratorio.setCaretColor(new java.awt.Color(51, 204, 255));
        laboratorio.setEnabled(false);
        laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioActionPerformed(evt);
            }
        });
        laboratorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                laboratorioKeyTyped(evt);
            }
        });

        Fraccionable.setBackground(new java.awt.Color(255, 204, 255));
        Fraccionable.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Fraccionable.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Fraccionable.setText("0");
        Fraccionable.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Fraccionable", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Fraccionable.setCaretColor(new java.awt.Color(51, 204, 255));
        Fraccionable.setEnabled(false);
        Fraccionable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FraccionableKeyTyped(evt);
            }
        });

        Descripcion.setBackground(new java.awt.Color(255, 255, 204));
        Descripcion.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Descripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Descripcion.setText("0");
        Descripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Descripcion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Descripcion.setCaretColor(new java.awt.Color(51, 204, 255));
        Descripcion.setEnabled(false);
        Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionActionPerformed(evt);
            }
        });
        Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DescripcionKeyTyped(evt);
            }
        });

        CantXPaq.setBackground(new java.awt.Color(255, 204, 255));
        CantXPaq.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        CantXPaq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CantXPaq.setText("0");
        CantXPaq.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Cant/paquete", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        CantXPaq.setCaretColor(new java.awt.Color(51, 204, 255));
        CantXPaq.setEnabled(false);
        CantXPaq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantXPaqKeyTyped(evt);
            }
        });

        PrecioUnit.setBackground(new java.awt.Color(255, 204, 255));
        PrecioUnit.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        PrecioUnit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PrecioUnit.setText("0");
        PrecioUnit.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Precio/Unidad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        PrecioUnit.setCaretColor(new java.awt.Color(51, 204, 255));
        PrecioUnit.setEnabled(false);
        PrecioUnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioUnitKeyTyped(evt);
            }
        });

        Stock.setBackground(new java.awt.Color(255, 255, 204));
        Stock.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Stock.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Stock.setText("0");
        Stock.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Stock", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Stock.setCaretColor(new java.awt.Color(51, 204, 255));
        Stock.setEnabled(false);
        Stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StockKeyTyped(evt);
            }
        });

        StockDetallado.setBackground(new java.awt.Color(255, 204, 255));
        StockDetallado.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        StockDetallado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        StockDetallado.setText("0");
        StockDetallado.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Fraccionable", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        StockDetallado.setCaretColor(new java.awt.Color(51, 204, 255));
        StockDetallado.setEnabled(false);
        StockDetallado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StockDetalladoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(Stock)
                .addGap(83, 83, 83)
                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(laboratorio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Presentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Insumos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(Descripcion, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(StockDetallado, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Costo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(Fraccionable, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CantXPaq, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtcodlabor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Insumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Presentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fraccionable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantXPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StockDetallado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodlabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros de laboratorios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        txtbusqueda.setBackground(new java.awt.Color(255, 204, 204));
        txtbusqueda.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        txtbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtbusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Realizar búsqueda de Formulas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        txtbusqueda.setCaretColor(new java.awt.Color(51, 204, 255));
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
        });

        jTableLaborat.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTableLaborat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "###", "Insumos", "Cantidad", "Costo", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLaborat.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableLaborat.getTableHeader().setReorderingAllowed(false);
        jTableLaborat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLaboratMouseClicked(evt);
            }
        });
        jTableLaborat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableLaboratKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLaborat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbusqueda)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Add.png"))); // NOI18N
        jMenu1.setText("NUEVO[F4]");
        jMenu1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/OK.png"))); // NOI18N
        jMenu2.setText("REGISTRAR[F5]");
        jMenu2.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Sync.png"))); // NOI18N
        jMenu3.setText("ACTUALIZAR[F6]");
        jMenu3.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Close.png"))); // NOI18N
        jMenu4.setText("CERRAR VENTANA");
        jMenu4.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyPressed

    }//GEN-LAST:event_NombreKeyPressed

    private void InsumosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsumosKeyPressed

    }//GEN-LAST:event_InsumosKeyPressed

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed

    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void jTableLaboratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLaboratMouseClicked
        int sel = this.jTableLaborat.getSelectedRow();
        this.txtcodlabor.setText(this.jTableLaborat.getValueAt(sel, 0).toString());
        this.Nombre.setText(this.jTableLaborat.getValueAt(sel, 1).toString());
        this.Insumos.setText(this.jTableLaborat.getValueAt(sel, 2).toString());

    }//GEN-LAST:event_jTableLaboratMouseClicked

    private void jTableLaboratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableLaboratKeyPressed

    }//GEN-LAST:event_jTableLaboratKeyPressed

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed

        this.jMenu1.setSelected(false);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed

        this.jMenu2.setSelected(false);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        if (this.txtcodlabor.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un laboratorio de la tabla.", "Seleccione laboratorio", JOptionPane.ERROR_MESSAGE);
        } else {

        }
        this.jMenu3.setSelected(false);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1

        System.out.println("Coordenadas: (" + ubicacion.x + "," + ubicacion.y + ")");//2
        setLocation((ubicacion.x - 0), (ubicacion.y) - 230);//3
        //239 268
    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked

    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        this.toFront();
        x = evt.getX();

        y = evt.getY();
    }//GEN-LAST:event_jMenuBar1MousePressed

    private void CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoActionPerformed

    private void CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoKeyTyped
        validator.solonumeros(evt, Costo, 3);
    }//GEN-LAST:event_CostoKeyTyped

    private void PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyTyped
        validator.solonumeros(evt, Precio, 3);
    }//GEN-LAST:event_PrecioKeyTyped

    private void CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadKeyPressed

    private void InsumosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsumosKeyReleased
   if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            controllerMedicamentos.setOp("S");
            controllerMedicamentos.setBusc(this.Insumos.getText());
            Formulas.txtcodlabor.setText(controllerMedicamentos.consultarMedicamentosXCodigo());
            this.Cantidad.requestFocus();
        };
    }//GEN-LAST:event_InsumosKeyReleased

    private void CantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyReleased
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
//                modelCompuestos.setOp("S");
//                modelCompuestos.setBusc(this.Buscar.getText());
//                ResultSet rs = modelCompuestos.queryCompuestos();
            
            //  if (rs.next()) {
//                    int r = this.jTableMedicamentosOp.getRowCount();
//                    System.out.println("next : " + rs.getString("###") + " Row : " + r);
            dtm = (DefaultTableModel) this.jTableLaborat.getModel();
            
            Object[] obj = new Object[3];
            obj[0] = this.txtcodlabor.getText();
            obj[1] = this.Insumos.getText();
            obj[2] = this.Cantidad.getText();
            dtm.addRow(obj);
            this.Cantidad.setText(null);
            this.Insumos.setText(null);
            this.Insumos.requestFocus();
            
            //}

        }
    }//GEN-LAST:event_CantidadKeyReleased

    private void PresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PresentacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentacionKeyTyped

    private void laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioActionPerformed

    private void laboratorioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laboratorioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioKeyTyped

    private void FraccionableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FraccionableKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_FraccionableKeyTyped

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionActionPerformed

    private void DescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescripcionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionKeyTyped

    private void CantXPaqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantXPaqKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CantXPaqKeyTyped

    private void PrecioUnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioUnitKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioUnitKeyTyped

    private void StockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_StockKeyTyped

    private void PresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentacionActionPerformed

    private void StockDetalladoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockDetalladoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_StockDetalladoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField CantXPaq;
    private javax.swing.JTextField Cantidad;
    public static javax.swing.JTextField Costo;
    public static javax.swing.JTextField Descripcion;
    public static javax.swing.JTextField Fraccionable;
    private javax.swing.JTextField Insumos;
    private javax.swing.JTextField Nombre;
    public static javax.swing.JTextField Precio;
    public static javax.swing.JTextField PrecioUnit;
    public static javax.swing.JTextField Presentacion;
    public static javax.swing.JTextField Stock;
    public static javax.swing.JTextField StockDetallado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableLaborat;
    public static javax.swing.JTextField laboratorio;
    private javax.swing.JTextField txtbusqueda;
    public static javax.swing.JTextField txtcodlabor;
    private javax.swing.JLabel txtmsg;
    // End of variables declaration//GEN-END:variables
}
