package vista;

import controlador.controllerProveedores;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMolinaDeveloper
 */
public class Proveedores extends javax.swing.JInternalFrame {

    public DefaultTableModel dtm;
private int x;
private int y;
    /**
     * Creates new form NewJInternalFrame
     */
    public Proveedores() {
        initComponents();
    }

    public void clear() {

        this.txtcodprovee.setText(null);
        this.Proveedor.setText(null);
        this.Correo.setText(null);
        this.Direccion.setText(null);
        this.Telefono.setText(null);
        this.Celular.setText(null);
        this.Ruc.setText(null);
        this.Proveedor.requestFocus();

    }

    public void insertProveedores() {
        if (validator.novacios("1-11", 2, this.Proveedor,this.Ruc) == false) {

            controllerProveedores.setOp("I");
            controllerProveedores.setCod(0);
            controllerProveedores.setNomb(this.Proveedor.getText());
            controllerProveedores.setCel(this.Celular.getText());
            controllerProveedores.setDir(this.Direccion.getText());
            controllerProveedores.setCorreo(this.Correo.getText());
            controllerProveedores.setFono(this.Telefono.getText());
            controllerProveedores.setRuc(this.Ruc.getText());
            
            this.txtmsg.setText(controllerProveedores.mntoProveedor());

            controllerProveedores.setOp("D");
            controllerProveedores.setBusc(this.Proveedor.getText());
            controllerProveedores.consultarProveedor("PROVEE",dtm);
            clear();
        }
    }

    public void updateProveedores() {
        if (validator.novacios("1-11", 2, this.Proveedor,this.Ruc) == false) {

            controllerProveedores.setOp("U");
            controllerProveedores.setCod(Integer.parseInt(this.txtcodprovee.getText()));
            controllerProveedores.setRuc(this.Ruc.getText());
            controllerProveedores.setNomb(this.Proveedor.getText());
            controllerProveedores.setCel(this.Celular.getText());
            controllerProveedores.setDir(this.Direccion.getText());
            controllerProveedores.setCorreo(this.Correo.getText());
            controllerProveedores.setFono(this.Telefono.getText());

            this.txtmsg.setText(controllerProveedores.mntoProveedor());

            controllerProveedores.setOp("D");
            controllerProveedores.setBusc(this.Proveedor.getText());
            controllerProveedores.consultarProveedor("PROVEE",dtm);
            clear();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Proveedor = new javax.swing.JTextField();
        txtcodprovee = new javax.swing.JTextField();
        Celular = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        txtmsg = new javax.swing.JLabel();
        Ruc = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablepoveedor = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registros de Proveedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/connections.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(928, 476));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar proveedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        Proveedor.setName("Proveedor");
        Proveedor.setBackground(new java.awt.Color(244, 245, 242));
        Proveedor.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Proveedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Proveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Proveedor", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Proveedor.setCaretColor(new java.awt.Color(51, 204, 255));
        Proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProveedorKeyPressed(evt);
            }
        });

        txtcodprovee.setEditable(false);
        txtcodprovee.setBackground(new java.awt.Color(255, 255, 204));
        txtcodprovee.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        txtcodprovee.setMaximumSize(new java.awt.Dimension(100, 28));
        txtcodprovee.setMinimumSize(new java.awt.Dimension(100, 28));
        txtcodprovee.setPreferredSize(new java.awt.Dimension(100, 28));

        Celular.setBackground(new java.awt.Color(244, 245, 242));
        Celular.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Celular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Celular.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Celular", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Celular.setCaretColor(new java.awt.Color(51, 204, 255));
        Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CelularKeyPressed(evt);
            }
        });

        Correo.setBackground(new java.awt.Color(244, 245, 242));
        Correo.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Correo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Correo Electrónico", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Correo.setCaretColor(new java.awt.Color(51, 204, 255));
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CorreoKeyPressed(evt);
            }
        });

        Telefono.setBackground(new java.awt.Color(244, 245, 242));
        Telefono.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Telefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Teléfono", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Telefono.setCaretColor(new java.awt.Color(51, 204, 255));
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelefonoKeyPressed(evt);
            }
        });

        Direccion.setBackground(new java.awt.Color(244, 245, 242));
        Direccion.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Direccion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Direccion.setCaretColor(new java.awt.Color(51, 204, 255));
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DireccionKeyPressed(evt);
            }
        });

        txtmsg.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        txtmsg.setForeground(new java.awt.Color(102, 0, 0));
        txtmsg.setText("DATOS CARGADOS.");
        txtmsg.setMaximumSize(new java.awt.Dimension(171, 16));
        txtmsg.setMinimumSize(new java.awt.Dimension(171, 16));
        txtmsg.setPreferredSize(new java.awt.Dimension(171, 16));
        txtmsg.setRequestFocusEnabled(false);

        Ruc.setName("Ruc");
        Ruc.setBackground(new java.awt.Color(244, 245, 242));
        Ruc.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Ruc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ruc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Ruc", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Ruc.setCaretColor(new java.awt.Color(51, 204, 255));
        Ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RucKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RucKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addComponent(Direccion)
                        .addComponent(Proveedor)
                        .addComponent(Ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtcodprovee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodprovee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros de proveedores", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        txtbusqueda.setBackground(new java.awt.Color(255, 204, 204));
        txtbusqueda.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        txtbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtbusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Realizar búsqueda de proveedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        txtbusqueda.setCaretColor(new java.awt.Color(51, 204, 255));
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
        });

        jTablepoveedor.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTablepoveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablepoveedor.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTablepoveedor.getTableHeader().setReorderingAllowed(false);
        jTablepoveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablepoveedorMouseClicked(evt);
            }
        });
        jTablepoveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablepoveedorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablepoveedor);
        if (jTablepoveedor.getColumnModel().getColumnCount() > 0) {
            jTablepoveedor.getColumnModel().getColumn(0).setResizable(false);
            jTablepoveedor.getColumnModel().getColumn(1).setResizable(false);
            jTablepoveedor.getColumnModel().getColumn(2).setResizable(false);
            jTablepoveedor.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(txtbusqueda))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Add.png"))); // NOI18N
        jMenu1.setText("NUEVO[F4]");
        jMenu1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/OK.png"))); // NOI18N
        jMenu2.setText("REGISTRAR[F5]");
        jMenu2.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Sync.png"))); // NOI18N
        jMenu3.setText("ACTUALIZAR[F6]");
        jMenu3.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Close.png"))); // NOI18N
        jMenu4.setText("CERRAR VENTANA");
        jMenu4.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablepoveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablepoveedorMouseClicked
        int sel = this.jTablepoveedor.getSelectedRow();
        this.txtcodprovee.setText(this.jTablepoveedor.getValueAt(sel, 0).toString());
        this.Proveedor.setText(this.jTablepoveedor.getValueAt(sel, 1).toString());
        this.Ruc.setText(this.jTablepoveedor.getValueAt(sel, 2).toString());
        this.Correo.setText(this.jTablepoveedor.getValueAt(sel, 6).toString());
        this.Direccion.setText(this.jTablepoveedor.getValueAt(sel, 3).toString());
        this.Telefono.setText(this.jTablepoveedor.getValueAt(sel, 4).toString());
        this.Celular.setText(this.jTablepoveedor.getValueAt(sel, 5).toString());
    }//GEN-LAST:event_jTablepoveedorMouseClicked

    private void ProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProveedorKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertProveedores();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateProveedores();
                }
            }

        }

    }//GEN-LAST:event_ProveedorKeyPressed

    private void RucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RucKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertProveedores();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateProveedores();
                }
            }

        }
    }//GEN-LAST:event_RucKeyPressed

    private void DireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertProveedores();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateProveedores();
                }
            }

        }
    }//GEN-LAST:event_DireccionKeyPressed

    private void CorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertProveedores();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateProveedores();
                }
            }

        }
    }//GEN-LAST:event_CorreoKeyPressed

    private void TelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertProveedores();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateProveedores();
                }
            }

        }
    }//GEN-LAST:event_TelefonoKeyPressed

    private void CelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertProveedores();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateProveedores();
                }
            }

        }
    }//GEN-LAST:event_CelularKeyPressed

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed
        controllerProveedores.setOp("D");
        controllerProveedores.setBusc(this.txtbusqueda.getText());
        controllerProveedores.consultarProveedor("PROVEE",dtm);
    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void jTablepoveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablepoveedorKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        }
    }//GEN-LAST:event_jTablepoveedorKeyPressed

    private void RucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RucKeyTyped
validator.solonumeros(evt, Ruc, 11);
    }//GEN-LAST:event_RucKeyTyped

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        clear();
        this.jMenu1.setSelected(false);
    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
       insertProveedores();
        this.jMenu2.setSelected(false);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        if(this.txtcodprovee.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Por favor seleccione un proveedor de la tabla.","Seleccione proveedor",JOptionPane.ERROR_MESSAGE);
        }else{       updateProveedores();}
        this.jMenu3.setSelected(false);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1

        System.out.println("Coordenadas: ("+ubicacion.x+","+ubicacion.y+")");//2
        setLocation((ubicacion.x-0), (ubicacion.y)-230);//3
        //239 268
    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked

    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        this.toFront();
        x = evt.getX();

        y = evt.getY();
    }//GEN-LAST:event_jMenuBar1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Celular;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Proveedor;
    private javax.swing.JTextField Ruc;
    private javax.swing.JTextField Telefono;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTablepoveedor;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcodprovee;
    private javax.swing.JLabel txtmsg;
    // End of variables declaration//GEN-END:variables
}
