package vista;

import controlador.controllerUsuarios;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMolinaDeveloper
 */
public class usuarios extends javax.swing.JInternalFrame {

    private int x;
    private int y;
    public DefaultTableModel dtm;

    /**
     * Creates new form NewJInternalFrame
     */
    public usuarios() {
        initComponents();
    }

    public void clear() {
        this.txtcodusuarios.setText(null);
        this.Nombres.setText(null);
        this.Dni.setText(null);
        this.Celular.setText(null);
        this.Direccion.setText(null);
        this.Usuario.setText(null);
        this.Contraseña.setText(null);
        this.Nombres.requestFocus();
    }

    public void insertUsuarios() {
        if (validator.novacios("20-8-9-20-5", 5, 4, this.Contraseña, this.Nombres, this.Dni, this.Celular, this.Direccion, this.Usuario) == false) {

            controllerUsuarios.setOp("I");
            controllerUsuarios.setCod(0);
            controllerUsuarios.setNomb(this.Nombres.getText());
            controllerUsuarios.setDni(this.Dni.getText());
            controllerUsuarios.setDir(this.Direccion.getText());
            controllerUsuarios.setCel(this.Celular.getText());
            controllerUsuarios.setPermisos(this.cmbacceso.getSelectedItem().toString());
            controllerUsuarios.setUser(this.Usuario.getText());
            String pwd = new String(this.Contraseña.getPassword());
            controllerUsuarios.setPwd(pwd.toString());
            this.txtmsg.setText(controllerUsuarios.mntoUsuarios());

            controllerUsuarios.consultarSession(dtm, "", this.Nombres.getText());
            clear();

        }
    }

    public void updateUsuarios() {
        if (validator.novacios("20-8-9-20-5", 5, this.Nombres, this.Dni, this.Celular, this.Direccion, this.Usuario) == false) {

            controllerUsuarios.setOp("U");
            controllerUsuarios.setCod(Integer.parseInt(this.txtcodusuarios.getText()));
            controllerUsuarios.setNomb(this.Nombres.getText());
            controllerUsuarios.setDni(this.Dni.getText());
            controllerUsuarios.setDir(this.Direccion.getText());
            controllerUsuarios.setCel(this.Celular.getText());
            controllerUsuarios.setPermisos(this.cmbacceso.getSelectedItem().toString());
            controllerUsuarios.setUser(this.Usuario.getText());
            String pwd = new String(this.Contraseña.getPassword());
            controllerUsuarios.setPwd(pwd.toString());
            main.lblusuario.setText(this.Nombres.getText());
            this.txtmsg.setText(controllerUsuarios.mntoUsuarios());
            controllerUsuarios.consultarSession(dtm, "", "");

            clear();
        }
    }

    public void teclasPresionadas(java.awt.event.KeyEvent evt) {
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_F5) {
                insertUsuarios();
            } else {
                if (evt.getExtendedKeyCode() == KeyEvent.VK_F6) {
                    updateUsuarios();
                }
            }

        }
    }

    public boolean soloNumeros() {
        try {
            int y = this.jTableUsuarios.getSelectedRow();

            return true;
        } catch (Exception ex) {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Nombres = new javax.swing.JTextField();
        Dni = new javax.swing.JTextField();
        Celular = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        cmbacceso = new javax.swing.JComboBox();
        txtcodusuarios = new javax.swing.JTextField();
        txtmsg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtbusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNuevo = new javax.swing.JMenu();
        jMenuIngresar = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/zoom.png"))); // NOI18N
        jMenuItem1.setText("DAR DE BAJA A ESTE USUARIO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registros de Usuarios");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/connections.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        Nombres.setName("Nombre");
        Nombres.setBackground(new java.awt.Color(244, 245, 242));
        Nombres.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Nombres.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Nombres.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Nombres[Mínimo 20 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Nombres.setCaretColor(new java.awt.Color(51, 204, 255));
        Nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombresKeyPressed(evt);
            }
        });

        Dni.setName("Dni");
        Dni.setBackground(new java.awt.Color(244, 245, 242));
        Dni.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Dni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Dni.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Dni[ 8 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Dni.setCaretColor(new java.awt.Color(51, 204, 255));
        Dni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DniKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DniKeyPressed(evt);
            }
        });

        Celular.setName("Celular");
        Celular.setBackground(new java.awt.Color(244, 245, 242));
        Celular.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Celular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Celular.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Celular-[ 9 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Celular.setCaretColor(new java.awt.Color(51, 204, 255));
        Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CelularKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CelularKeyPressed(evt);
            }
        });

        Usuario.setName("Usuario");
        Usuario.setBackground(new java.awt.Color(255, 255, 153));
        Usuario.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Usuario[Mínimo de 5 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Usuario.setCaretColor(new java.awt.Color(51, 204, 255));
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioKeyPressed(evt);
            }
        });

        Direccion.setName("Direccion");
        Direccion.setBackground(new java.awt.Color(244, 245, 242));
        Direccion.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Direccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Direccion[Mínimo de 20 caracteres]", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Direccion.setCaretColor(new java.awt.Color(51, 204, 255));
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DireccionKeyPressed(evt);
            }
        });

        Contraseña.setBackground(new java.awt.Color(255, 255, 153));
        Contraseña.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Contraseña[Mínimo de 4 caracteres]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContraseñaKeyPressed(evt);
            }
        });

        cmbacceso.setBackground(new java.awt.Color(255, 255, 153));
        cmbacceso.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        cmbacceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "SUPER", "DESPC" }));
        cmbacceso.setSelectedIndex(2);
        cmbacceso.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Permisos ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        cmbacceso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbaccesoKeyPressed(evt);
            }
        });

        txtcodusuarios.setEditable(false);
        txtcodusuarios.setBackground(new java.awt.Color(255, 255, 204));
        txtcodusuarios.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        txtcodusuarios.setMaximumSize(new java.awt.Dimension(100, 28));
        txtcodusuarios.setMinimumSize(new java.awt.Dimension(100, 28));
        txtcodusuarios.setPreferredSize(new java.awt.Dimension(100, 28));

        txtmsg.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        txtmsg.setForeground(new java.awt.Color(102, 0, 0));
        txtmsg.setText("DATOS CARGADOS.");
        txtmsg.setMaximumSize(new java.awt.Dimension(171, 16));
        txtmsg.setMinimumSize(new java.awt.Dimension(171, 16));
        txtmsg.setPreferredSize(new java.awt.Dimension(171, 16));
        txtmsg.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbacceso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtcodusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Usuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Contraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbacceso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros de usuarios", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 1, 12))); // NOI18N

        txtbusqueda.setBackground(new java.awt.Color(255, 204, 204));
        txtbusqueda.setFont(new java.awt.Font("Calibri Light", 2, 12)); // NOI18N
        txtbusqueda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtbusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Realizar búsqueda de usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri Light", 0, 12))); // NOI18N
        txtbusqueda.setCaretColor(new java.awt.Color(51, 204, 255));
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableUsuarios.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.setComponentPopupMenu(jPopupMenu1);
        jTableUsuarios.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jTableUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableUsuariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(2).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jMenuBar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseDragged(evt);
            }
        });
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuBar1MousePressed(evt);
            }
        });

        jMenuNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Add.png"))); // NOI18N
        jMenuNuevo.setText("NUEVO[F4]");
        jMenuNuevo.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenuNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuNuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenuNuevo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenuNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuNuevoMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuNuevo);

        jMenuIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/OK.png"))); // NOI18N
        jMenuIngresar.setText("REGISTRAR[F5]");
        jMenuIngresar.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenuIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuIngresar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenuIngresar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenuIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuIngresarMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuIngresar);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Sync.png"))); // NOI18N
        jMenu3.setText("ACTUALIZAR[F6]");
        jMenu3.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/cambio.png"))); // NOI18N
        jMenu5.setText("CAMBIAR USUARIO & CONTRASENA");
        jMenu5.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Close.png"))); // NOI18N
        jMenu4.setText("CERRAR VENTANA");
        jMenu4.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        int sel = this.jTableUsuarios.getSelectedRow();
        this.txtcodusuarios.setText(this.jTableUsuarios.getValueAt(sel, 0).toString());

        this.Nombres.setText(this.jTableUsuarios.getValueAt(sel, 1).toString());
        this.Dni.setText(this.jTableUsuarios.getValueAt(sel, 2).toString());
        this.Direccion.setText(this.jTableUsuarios.getValueAt(sel, 3).toString());
        this.Celular.setText(this.jTableUsuarios.getValueAt(sel, 4).toString());
        this.cmbacceso.setSelectedItem(this.jTableUsuarios.getValueAt(sel, 5).toString());
        this.Usuario.setText(this.jTableUsuarios.getValueAt(sel, 6).toString());
        this.Contraseña.setText(null);
        this.Contraseña.setEnabled(false);
        this.txtmsg.setText(this.jTableUsuarios.getValueAt(sel, 8).toString().equals("INACTIVO") ? "Usuario Inactivo" : "Usuario Activo");

    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void DniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyTyped
        validator.solonumeros(evt, Dni, 8);
    }//GEN-LAST:event_DniKeyTyped

    private void NombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombresKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_NombresKeyPressed

    private void DniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DniKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_DniKeyPressed

    private void CelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_CelularKeyPressed

    private void DireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_DireccionKeyPressed

    private void UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_UsuarioKeyPressed

    private void ContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_ContraseñaKeyPressed

    private void cmbaccesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbaccesoKeyPressed
        teclasPresionadas(evt);
    }//GEN-LAST:event_cmbaccesoKeyPressed

    private void jTableUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableUsuariosKeyPressed
        if (evt.getExtendedKeyCode() == KeyEvent.VK_F4) {
            clear();
        }
    }//GEN-LAST:event_jTableUsuariosKeyPressed

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed
        controllerUsuarios.consultarSession(dtm, "", this.Nombres.getText());
    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String x = this.jTableUsuarios.getValueAt(this.jTableUsuarios.getSelectedRow(), 5).toString();
        if (x.equals("ADMIN")) {
            JOptionPane.showMessageDialog(null, "Un usuario con permisos de administrador no puede ser eliminado.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            controllerUsuarios.setOp("B");
            controllerUsuarios.setCod(Integer.parseInt(this.txtcodusuarios.getText()));
            this.txtmsg.setText(controllerUsuarios.mntoUsuarios());
            controllerUsuarios.consultarSession(dtm, "", this.Nombres.getText());
            clear();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            System.out.print("Button 3");
//if(soloNumeros()==false){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila de la tabla,para dar de baja a un usuario", "Seleccionar", JOptionPane.INFORMATION_MESSAGE);
//}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void CelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelularKeyTyped
        validator.solonumeros(evt, Celular, 9);
    }//GEN-LAST:event_CelularKeyTyped

    private void jMenuNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNuevoMousePressed
        clear();
        this.Contraseña.setEnabled(true);
        this.jMenuNuevo.setSelected(false);
    }//GEN-LAST:event_jMenuNuevoMousePressed

    private void jMenuIngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIngresarMousePressed
        int x = 0;
        while (x < this.jTableUsuarios.getRowCount()) {

            if (this.Usuario.getText().equals(this.jTableUsuarios.getValueAt(x, 6).toString())) {
                JOptionPane.showMessageDialog(null, "Usuario existente,cambie el nombre de usuario.", "Error al intentar registrar", JOptionPane.ERROR_MESSAGE);

            } else {
                if (this.Nombres.getText().equals(this.jTableUsuarios.getValueAt(x, 1).toString())) {
                    JOptionPane.showMessageDialog(null, "Persona existente,no se realizara ninguna inserción.", "Error al intentar registrar", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (this.Dni.getText().equals(this.jTableUsuarios.getValueAt(x, 2).toString())) {
                        JOptionPane.showMessageDialog(null, "Dni existente,no se realizara ninguna inserción.", "Error al intentar registrar", JOptionPane.ERROR_MESSAGE);
                    } else {
                        insertUsuarios();
                    }
                }
            }
            x++;
        }


        this.jMenuIngresar.setSelected(false);
    }//GEN-LAST:event_jMenuIngresarMousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
         if (this.txtcodusuarios.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario de la tabla.", "Seleccione usuario", JOptionPane.ERROR_MESSAGE);
        } else {
            updateUsuarios();
        }

        this.jMenu3.setSelected(false);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MousePressed
        this.dispose();
    }//GEN-LAST:event_jMenu4MousePressed

    private void jMenuBar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1

        System.out.println("Coordenadas: (" + ubicacion.x + "," + ubicacion.y + ")");//2
        setLocation((ubicacion.x - 0), (ubicacion.y) - 230);//3
        //239 268
    }//GEN-LAST:event_jMenuBar1MouseDragged

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked

    }//GEN-LAST:event_jMenuBar1MouseClicked

    private void jMenuBar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MousePressed
        this.toFront();
        x = evt.getX();

        y = evt.getY();
    }//GEN-LAST:event_jMenuBar1MousePressed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed

        JLabel jUser = new JLabel("Usuario");
        JTextField usuarior = new JTextField();
        JLabel jPassword = new JLabel("Password");
        JPasswordField passwordr = new JPasswordField();
        Object[] ob = {jUser, usuarior, jPassword, passwordr};
        usuarior.requestFocus();
        int result = JOptionPane.showConfirmDialog(this, ob, "Ingrese su USUARIO y CONTRASENA actual", JOptionPane.OK_CANCEL_OPTION);
 
        if (result == JOptionPane.OK_OPTION) {
            try {
                //COMPRUEBO LA AUTENTICIDAD

                String pwd = new String(passwordr.getPassword());
                controllerUsuarios.setBusc("");
                controllerUsuarios.setOp("L");
                controllerUsuarios.setUser(usuarior.getText());
                controllerUsuarios.setPwd(pwd);
                ResultSet rs = controllerUsuarios.consultarSession();
//             
                if (rs.next()) {
                    System.out.println("Autenticado...");
                    String codigo = rs.getString("###");
                    usuarior.setText(null);
                    passwordr.setText(null);
                    int resul = JOptionPane.showConfirmDialog(this, ob, "Nuevo usuario & contraseña ", JOptionPane.OK_CANCEL_OPTION);
                    if (resul == JOptionPane.OK_OPTION) {

                        controllerUsuarios.setOp("A");
                        controllerUsuarios.setCod(Integer.parseInt(codigo));
                        controllerUsuarios.setUser(usuarior.getText());
                        String pwdd = new String(passwordr.getPassword());
                        controllerUsuarios.setPwd(pwdd.toString());
                        this.txtmsg.setText(controllerUsuarios.mntoUsuarios());

                        controllerUsuarios.consultarSession(dtm, "", this.Nombres.getText());
                        clear();
                        JOptionPane.showMessageDialog(null, "Exito al actualizar.", "Datos actualizados", JOptionPane.INFORMATION_MESSAGE);

                    }
                }else{
                    JOptionPane.showMessageDialog(this,"Usuario o contraseña incorrecta.","Datos invalidos",JOptionPane.ERROR_MESSAGE);
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jMenu5MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Celular;
    public static final javax.swing.JPasswordField Contraseña = new javax.swing.JPasswordField();
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Dni;
    private javax.swing.JTextField Nombres;
    private javax.swing.JTextField Usuario;
    public static javax.swing.JComboBox cmbacceso;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuIngresar;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenu jMenuNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableUsuarios;
    public static javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcodusuarios;
    private javax.swing.JLabel txtmsg;
    // End of variables declaration//GEN-END:variables
}
